name: Checkov Scan and Terraform Plan
permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  pull_request:
    branches: [ main ]

jobs:

  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkov Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          check: 'MEDIUM,HIGH,CRITICAL'
          api-key: ${{ secrets.CHECKOV_API_KEY }}
 
  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: scan
    strategy:
      fail-fast: true
      matrix:
        path:
          - 00-SetupRemoteState
          - 01-EKS-cluster
          - 02-helm-EBS-CLI-driver-install
          - 03-Fleetman-Microservices
      max-parallel: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-duration-seconds: 900
          aws-region: us-east-1 
      
      - name: Check Remote State Existence
        if: matrix.path == '00-SetupRemoteState'  
       # shouldnt be needed on a non-test/non-ephemeral environment
        run: |
          cd EKS-Microservice-Terraformed/${{ matrix.path }}
          pip install boto3
          python check_state_exists.py
      
      - name: Initialize Terraform
        run: |
          cd EKS-Microservice-Terraformed/${{ matrix.path }}
          terraform init -input=false

      - name: Plan Terraform
        id: plan
        run: |
          cd EKS-Microservice-Terraformed/${{ matrix.path }}
          terraform plan -input=false -no-color -out=tfplan && terraform show -no-color tfplan

      - name: Apply Remote State only (if missing)
        # shouldnt be needed on a non-test/non-ephemeral environment
        if: steps.plan.outcome == 'success' && matrix.path == '00-SetupRemoteState' && env.REMOTE_STATE_EXISTS == 'False'
        id: apply-remote-state
        run: |
          cd EKS-Microservice-Terraformed/${{ matrix.path }}
          terraform apply \
            -input=false \
            -no-color \
            tfplan
                  
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: True
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ##  ${{ matrix.path }} TF plan on ${{ steps.branch-name.outputs.current_branch }} branch (Triggered by ${{github.actor}})
            ```
            ${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}
            ```